---
HOSTS:
  el7:
    roles:
    - default
    - master
    - client
    platform: el-7-x86_64
    box: centos/7
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    yum_repos:
      epel:
        mirrorlist: https://mirrors.fedoraproject.org/mirrorlist?repo=epel-7&arch=$basearch&country=us
        gpgkeys:
        - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
    family: centos-cloud/centos-7
    gce_machine_type: n1-standard-2
  el6:
    roles:
    - client
    platform: el-6-x86_64
    box: centos/6
    hypervisor: vagrant
    yum_repos:
      epel:
        mirrorlist: https://mirrors.fedoraproject.org/mirrorlist?repo=epel-6&arch=$basearch&country=us
        gpgkeys:
        - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
CONFIG:
  log_level: verbose
  type: aio
  vagrant_memsize: 256
  puppet_collection: "<%= ENV.fetch('BEAKER_PUPPET_COLLECTION', 'puppet7') %>"
